[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"

[project]
name = "streamlit-firebase-auth"
version = "1.1.5"
authors = [
    {name="Suzuki Shogo", email="suzuki.shogo@commondo.jp"},
]
description = "Streamlit component for Firebae auth"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires = [
    "firebase-admin"
]
dependencies = [
    "build>=1.2.2.post1",
    "firebase-admin",
    "twine>=6.1.0",
]

[project.urls]
"Homepage" = "https://github.com/munaita-0/streamlit-firebase-auth"

[tool.hatch.build.targets.sdist]
artifacts = [
    "streamlit_firebase_auth/frontend/build/",
]

[tool.hatch.build.targets.wheel]
artifacts = [
    "streamlit_firebase_auth/frontend/build/",
]
